Num1 = input("Antaisitko kolme kokonaislukua, ensimmäinen luku:")
Num1Str = float(Num1)
Num2 = input("Toinen luku:")
Num2Str = float(Num2)
Num3 = input("Kolmas luku:")
Num3Str = float(Num3)
NumSum = (Num1Str+Num2Str+Num3Str)
NumMulti = (Num1Str*Num2Str*Num3Str)
NumAvg = ((Num1Str+Num2Str+Num3Str)/3)
input ("Kolmen kokonaisluvun summa on "+str(NumSum)+", lukujen tulo on "+str(NumMulti)+", ja lukujen keskiarvo on "+str(NumAvg))
